server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.221.66.174:3308/phonebookdb1
    username: gangnam
    password: gangnam
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
